// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: uploader.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Uploader {
  public static partial class UploadService
  {
    static readonly string __ServiceName = "uploader.UploadService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Uploader.UploadRequest> __Marshaller_uploader_UploadRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Uploader.UploadRequest.Parser));
    static readonly grpc::Marshaller<global::Uploader.UploadResponse> __Marshaller_uploader_UploadResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Uploader.UploadResponse.Parser));

    static readonly grpc::Method<global::Uploader.UploadRequest, global::Uploader.UploadResponse> __Method_Upload = new grpc::Method<global::Uploader.UploadRequest, global::Uploader.UploadResponse>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "Upload",
        __Marshaller_uploader_UploadRequest,
        __Marshaller_uploader_UploadResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Uploader.UploaderReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of UploadService</summary>
    [grpc::BindServiceMethod(typeof(UploadService), "BindService")]
    public abstract partial class UploadServiceBase
    {
      /// <summary>
      /// client stream
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Uploader.UploadResponse> Upload(grpc::IAsyncStreamReader<global::Uploader.UploadRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for UploadService</summary>
    public partial class UploadServiceClient : grpc::ClientBase<UploadServiceClient>
    {
      /// <summary>Creates a new client for UploadService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public UploadServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for UploadService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public UploadServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected UploadServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected UploadServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// client stream
      /// </summary>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncClientStreamingCall<global::Uploader.UploadRequest, global::Uploader.UploadResponse> Upload(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Upload(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// client stream
      /// </summary>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncClientStreamingCall<global::Uploader.UploadRequest, global::Uploader.UploadResponse> Upload(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_Upload, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override UploadServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new UploadServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(UploadServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Upload, serviceImpl.Upload).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, UploadServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Upload, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::Uploader.UploadRequest, global::Uploader.UploadResponse>(serviceImpl.Upload));
    }

  }
}
#endregion
